num = int(input('Digite um numero em metros :'))
print ('correspondente ao valor {}M'.format(num))
print ('Temos {}DM'.format(num*10))
print ('Temos {}CM'.format(num*100))
print ('Temos {}MM'.format(num*1000))
print ('Temos {]')