nome = str(input('Digite seu nome: ')).title().strip()
print('Analisando seu nome ....')
print('Seu nome em maiusculas fica {}'.format(nome.upper()))
print('Seu nome em minusculas fica {}'.format(nome.lower()))
print('Seu nome tem ao todo {}'.format(len(nome)-nome.count(' ')))
lista = nome.split() 
print('Seu primeiro nome é {} e ele tem {} letras'.format(lista [0], len(lista[0])))